# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-27 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20171122_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='host',
        ),
    ]
